<ips:template parameters="" />
<h3 class="ipsType_reset ipsWidget_title">{lang="current_donation_goals"}</h3>

<div class='ipsWidget_inner'>
	<ul class='ipsDataList'>
		{{foreach \IPS\nexus\Donation\Goal::roots() as $goal}}
			<li class="ipsDataItem">
				<a href="{url="app=nexus&module=clients&controller=donations&do=donate&id={$goal->_id}" seoTemplate="clientsdonate" seoTitle="\IPS\Http\Url\Friendly::seoTitle( $goal->_title )" protocol="\IPS\Settings::i()->nexus_https"}" class="ipsType_blendLinks" data-ipsDialog data-ipsDialog-title="{$goal->_title}">
					<div class='ipsDataItem_main'>
						<div class='ipsType_large ipsType_break ipsType_blendLinks'>{$goal->_title}</div>
						{{if $goal->goal}}
								<div class="ipsType_center ipsSpacer_top">
									<div class="cDonateProgressBar cDonateProgressBar_condensed">
										<div class="cDonateProgressBar_progress" style="width:{expression="100/$goal->goal*$goal->current"}%"></div>
									</div>
									<span class="ipsType_light ipsType_small">
										{lang="donate_progress" htmlsprintf="new \IPS\nexus\Money( $goal->current, $goal->currency ), new \IPS\nexus\Money( $goal->goal, $goal->currency )"}
									</span>
								</div>
						{{else}}
							<div class="ipsType_light ipsType_small">
								{lang="donate_sofar" htmlsprintf="new \IPS\nexus\Money( $goal->current, $goal->currency )"}
							</div>
						{{endif}}
					</div>
				</a>
			</li>
		{{endforeach}}
	</ul>
</div>