<ips:template parameters="$terms, $privacy, $form" />
{theme="ipsfocus_b1"}
<h2 class="ipsType_sectionTitle">
    {{if $terms and $privacy}}
		{lang="reconfirm_terms_and_policy_blurb"}
	{{elseif $terms}}
		{lang="reconfirm_terms_blurb"}
	{{else}}
		{lang="reconfirm_privacy_blurb"}
	{{endif}}
</h2>
{theme="ipsfocus_b2"}<div class='ipsPad'>

{{if $terms}}
	<div class="ipsSpacer_bottom">
		<h2 class="ipsType_sectionHead">{lang="reg_terms"}</h2>
		<div class='ipsType_normal ipsType_richText ipsPad'>
			{lang="reg_rules_value"}
		</div>
	</div>
{{endif}}

{{if $privacy}}
	<div class="ipsSpacer_bottom">
		<h2 class="ipsType_sectionHead">{lang="privacy"}</h2>
		<div class='ipsType_normal ipsType_richText ipsPad'>
			{lang="privacy_text_value"}
			{{if \IPS\Settings::i()->site_address and \IPS\Settings::i()->site_address != "null"}}
				<p>{setting="board_name"}, {address="\IPS\Settings::i()->site_address"}</p>
			{{endif}}
		</div>
	</div>
{{endif}}

{$form|raw}


</div>{theme="ipsfocus_b3"}