<ips:template parameters="$table, $headers, $images" />

{{foreach $images as $image}}
	<li class='{{if $image->hidden()}}ipsModerated{{else}}ipsAreaBackground_reset{{endif}} ipsPad ipsType_center cGalleryImageItem ipsContained ipsType_break'>
		<a href='{$image->url()}' title='{lang="view_this" sprintf="$image->caption"}'>
			<img src='{file="$image->medium_file_name" extension="gallery_Images"}' alt='' class='ipsImage'>
		</a>
		<h2 class='ipsType_sectionHead ipsType_normal'>
			{{if $image->unread()}}<span class='ipsItemStatus ipsItemStatus_small'><i class="fa fa-circle"></i></span>{{endif}}
			{{if $image->prefix()}}
				{template="prefix" group="global" app="core" params="$image->prefix( TRUE ), $image->prefix()"}
			{{endif}}
			<div class='ipsContained ipsType_break'>
				<a href='{$image->url()}' title='{lang="view_this" sprintf="$image->caption"}' class='ipsTruncate ipsTruncate_line'>
					{{if $image->unread()}}<strong>{$image->caption}</strong>{{else}}{$image->caption}{{endif}}
				</a>
			</div>
			{{if $table->canModerate()}}
				<input type='checkbox' data-role='moderation' name="moderate[{$image->id}]" data-actions="{{if $image->mapped('featured')}}unfeature{{else}}feature{{endif}} {{if $image->mapped('pinned')}}unpin{{else}}pin{{endif}} {{if $image->hidden() === -1}}unhide{{elseif $image->hidden() === 1}}approve{{else}}hide{{endif}} {{if $image->mapped('locked')}}unlock{{else}}lock{{endif}} move delete" data-state='{{if $image->tableStates()}}{$image->tableStates()}{{endif}}'>
			{{endif}}
		</h2>
		<ul class='ipsList_inline'>
			{{if $image->directContainer()->allow_comments}}
				<li class='{{if $image->comments == 0}}ipsFaded{{endif}}' data-ipsTooltip title='{lang="num_comments" pluralize="$image->comments"}'><i class='fa fa-comment'></i> {$image->comments}</li>
			{{endif}}
			<li class='{{if $image->views == 0}}ipsFaded{{endif}}' data-ipsTooltip title='{lang="num_views_with_number" pluralize="$image->views"}'><i class='fa fa-eye'></i> {$image->views}</li>
		</ul>
		{{if $image->mapped('pinned') || $image->mapped('featured') || $image->hidden() === -1 || $image->hidden() === 1}}
			<br>
			<ul class='ipsList_inline'>
				<li>
					{{if $image->hidden() === -1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$image->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
					{{elseif $image->hidden() === 1}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
					{{endif}}							
					{{if $image->mapped('pinned')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="pinned"}'><i class='fa fa-thumb-tack'></i></span>
					{{endif}}
					{{if $image->mapped('featured')}}
						<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>
					{{endif}}
				</li>
			</ul>
		{{endif}}
	</li>
{{endforeach}}
