<ips:template parameters="$member, $types, $currentAppModule, $currentType, $table" />
<div class='ipsBox ipsfocus_reset'>
	{theme="ipsfocus_b1"}<h2 class='ipsType_sectionTitle ipsType_reset'>{{if !$currentAppModule}}{lang="all_content_by_user" sprintf="$member->name"}{{else}}{lang="content_by_user" sprintf="\IPS\Member::loggedIn()->language()->addToStack( $types[ $currentAppModule ][ $currentType ]::$title . '_pl' ), $member->name"}{{endif}}</h2>{theme="ipsfocus_b2"}
	{$table|raw}
  {theme="ipsfocus_b3"}
</div>