<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm {$class} ipsPad" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}
	{{foreach $elements['streams'] as $input}}
		<ul class='ipsList_reset'>
			{$input->html($form)|raw}
		</ul>
	{{endforeach}}
	<div id="elFilterFormFull" class="{{if isset( $elements['streams'] )}}ipsJS_hide{{endif}}">
		{{if isset( $elements['title'] )}}
			{{foreach $elements['title'] as $input}}
				<ul class='ipsList_reset'>
					{$input->rowHtml($form)|raw}
				</ul>
			{{endforeach}}
		{{endif}}
		<div class="ipsGrid ipsSpacer_bottom">
			{{foreach $elements as $tabName => $collection}}
				{{if $tabName != 'streams' and $tabName != 'title'}}
					<div class="ipsGrid_span3">
						<ul class='ipsList_reset'>
							{{foreach $collection as $input}}
								{{if $input instanceof \IPS\Helpers\Form\CheckboxSet}}
									<li class='ipsFieldRow ipsPad_half ipsClearfix' data-controller="nexus.admin.support.filterCheckboxSet">
										<div class="ipsClearfix">
											<div>
												<span class='ipsFieldRow_title'>{lang="$input->name"}</span>
												&nbsp;
												<a href="#all" class="ipsJS_show" data-action="checkAll">{lang="all"}</a> &middot; <a href="#all" class="ipsJS_show" data-action="checkNone">{lang="none"}</a>
											</div>
										</div>
										<div class='ipsFieldRow_content {{if $input->error}}ipsFieldRow_error{{endif}}'>
											{$input->html(TRUE)|raw}
										</div>
									</li>
								{{elseif is_object( $input ) }}
									{$input->rowHtml($form)|raw}
								{{else}}
									{$input|raw}
								{{endif}}
							{{endforeach}}
						</ul>
					</div>
				{{endif}}
			{{endforeach}}
		</div>
		{expression="implode( '', $actionButtons)" raw="true"}
	</div>
</form>
<div class="ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide" id="elSaveStream_menu">
	<form action="{url="app=nexus&module=support&controller=requests&do=saveStream"}" method="post">
		<div class="ipsPad">
			<input type="text" name="stream_title" placeholder="{lang="stream_title"}">
		</div>
		<div class="ipsAreaBackground ipsPad_half ipsType_center">
			<input type="submit" class="ipsButton ipsButton_small ipsButton_primary" value="{lang="save"}">
		</div>
	</form>
</div>