<ips:template parameters="$form, $stream, $results, $pagination, $groupByDepartment, $sortBy, $sortDir, $tracked, $participatedIn" />

<div data-controller='nexus.admin.support.list'>
	<div class="ipsAreaBackground_light ipsSpacer_bottom ipsJS_show" data-role="filterForm">
		{$form|raw}
	</div>
	<noscript>
		<p class="ipsType_reset ipsType_normal ipsSpacer_bottom" data-role="filterBlurb">{$stream->title} <a href="{url="app=nexus&module=support&controller=requests&do=filters"}" data-action="showFilterForm" class="ipsType_small">({lang="change"})</a></p>
	</noscript>

	<div data-role='mainTable'>
		{template="requestsTable" group="support" params="$results, $pagination, $groupByDepartment, $sortBy, $sortDir, $tracked, $participatedIn"}
	</div>
</div>