<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<div data-controller='gallery.front.submit.chooseCategory' data-preselected-album="{expression="\IPS\Request::i()->album"}" class='cGallerySubmit_chooseCategory'>
	<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
		<input type="hidden" name="{$id}_submitted" value="1">
		{{foreach $hiddenValues as $k => $v}}
			{{if is_array($v)}}
				{{foreach $v as $_k => $_v}}
					<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
				{{endforeach}}
			{{else}}
				<input type="hidden" name="{$k}" value="{$v}">
			{{endif}}
		{{endforeach}}
		<div class='ipsGrid ipsGrid_collapsePhone ipsPad cGallerySubmit_albumChoice'>
			<div class='ipsGrid_span12'>
				<h2 class='ipsType_pageTitle ipsType_center ipsSpacer_bottom'>{lang="choose_category"}</h2>
				{$elements['']['image_category']->html()|raw}
			</div>
		</div>
		<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center ipsJS_hide" data-role="continueCategory">
			{{foreach $actionButtons as $button}}
				{$button|raw}
			{{endforeach}}
		</div>
	</form>
</div>