<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />

<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm data-role="allImagesForm">
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}
	<div class='ipsAreaBackground ipsPad cGallerySubmit_bottomBar' id='elGallerySubmit_bottomBar'>
		<ul class='ipsList_inline'>
			<li>
				<a href='#' class='ipsButton ipsButton_veryLight ipsButton_large' id='elCopyrightMenu' data-ipsMenu data-ipsMenu-appendTo='#elGallerySubmit_bottomBar' data-ipsMenu-above='true' data-ipsMenu-closeOnClick='false'>{lang="set_copyright_all"} <i class='fa fa-caret-up'></i></a>
			</li>
			<li>
				<a href='#' class='ipsButton ipsButton_veryLight ipsButton_large' id='elCreditMenu' data-ipsMenu data-ipsMenu-appendTo='#elGallerySubmit_bottomBar' data-ipsMenu-above='true' data-ipsMenu-closeOnClick='false'>{lang="set_credit_all"} <i class='fa fa-caret-up'></i></a>
			</li>
			<li>
				{$elements['']['image_auto_follow']->html()|raw} <label for='check_image_auto_follow'>{lang="new_image_comments_notification"}</label>
			</li>
			<li class='ipsPos_right'>
				<button type='submit' class='ipsButton ipsButton_primary ipsButton_large' data-action='finish'><i class='fa fa-check'></i> {lang="image_info_finish"}</button>
			</li>
		</ul>
	</div>

	<div class='ipsMenu ipsMenu_wide ipsPad ipsHide' id='elCopyrightMenu_menu'>
		<h3 class='ipsType_sectionHead'>{lang="copyright"}</h3>
		<p class='ipsType_reset ipsSpacer_bottom'>{lang="set_copyright_desc"}</p>

		{$elements['']['image_copyright']->html()|raw}
	</div>

	<div class='ipsMenu ipsMenu_wide ipsPad ipsHide' id='elCreditMenu_menu'>
		<h3 class='ipsType_sectionHead'>{lang="credit"}</h3>
		<p class='ipsType_reset ipsSpacer_bottom'>{lang="credit_desc"}</p>

		{$elements['']['image_credit_info']->html()|raw}
	</div>
</form>
