<ips:template parameters="$table, $headers, $rows" />

{{foreach $rows as $row}}
	<li>
		<p class='ipsType_reset ipsType_normal ipsTruncate ipsTruncate_line'>
			{{if $row['card_type'] == 'american_express' OR $row['card_type'] == 'diners_club'}}XXXX-XXXXXX-X{$row['card_number']}{{else}}XXXX-XXXX-XXXX-{$row['card_number']}{{endif}}
		</p>
		<span class='ipsType_medium ipsType_light ipsTruncate ipsTruncate_line'>{{if $row['card_type']}}{lang="card_type_{$row['card_type']}"}{{else}}{lang="card_type_generic"}{{endif}}{{if $row['card_expires']}}, expires {$row['card_expire']}{{endif}}</span>
	</li>
{{endforeach}}