<ips:template parameters="$table, $headers, $rows, $quickSearch" />
{{if count( $rows )}}
	<ol class='ipsClear ipsList_reset cCustomerHistory {{foreach $table->classes as $class}}{$class} {{endforeach}}' id='elTable_{$table->uniqueId}' data-role="tableRows" itemscope itemtype="http://schema.org/ItemList">
		{template="$table->rowsTemplate[1]" params="$table, $headers, $rows" object="$table->rowsTemplate[0]"}
	</ol>
{{endif}}
<div class='ipsClearfix'>
	{{if $table->pages > 1}}
		{{if !isset( request.do ) or request.do != 'history'}}
			<div class="ipsType_center ipsAreaBackground_light ipsPad">
				<a href="{$table->baseUrl}" class="ipsButton ipsButton_verySmall ipsButton_normal">{lang="see_all_history"}</a>
			</div>
		{{else}}
			<div data-role="tablePagination">
				{template="pagination" group="global" app="core" location="global" params="$table->baseUrl, $table->pages, $table->page, $table->limit"}
			</div>
		{{endif}}
	{{endif}}
</div>