<ips:template parameters="$blog" />

<div id='elBlogHeader'>
	{$blog->coverPhoto()|raw}
</div>
<div id='elBlogHeaderStats' class='ipsPad'>
	<div>
		<div class='ipsPos_right ipsResponsive_noFloat ipsResponsive_hidePhone'>
		{template="follow" app="core" group="global" params="'blog', 'blog', $blog->_id, \IPS\blog\Entry::containerFollowerCount( $blog )"}
		</div>
		<ul class='ipsGrid cBlockView_stats'>
			<li class='ipsGrid_span4'>
				<strong class='ipsType_minorHeading'>{lang="blog_entries" pluralize="$blog->_items"}</strong><br>
				<strong class='ipsType_normal'>{number="$blog->_items"}</strong>
			</li>
			<li class='ipsGrid_span4'>
				<strong class='ipsType_minorHeading'>{lang="blog_comments" pluralize="$blog->_comments"}</strong><br>
				<strong class='ipsType_normal'>{number="$blog->_comments"}</strong>
			</li>
			<li class='ipsGrid_span4'>
				<strong class='ipsType_minorHeading'>{lang="blog_views" pluralize="$blog->num_views"}</strong><br>
				<strong class='ipsType_normal'>{number="$blog->num_views"}</strong>
			</li>
		</ul>
	</div>
	{{if !( $blog->owner() instanceof \IPS\Member ) and count( $blog->contributors() )}}
		<div class='cBlogContributors ipsClearfix ipsResponsive_hidePhone'>
			<h2 class='ipsType_minorHeading'>{lang="contributors_to_this"}</h2>
			<ul class='cBlogView_contributors'>
				{{foreach  $blog->contributors() as $idx => $contributor}}
					<li class=''>
						<span data-ipsTooltip title='{$contributor['member']->name}'>
							{template="userPhoto" group="global" app="core" params="$contributor['member'], 'mini'"}<span class='ipsNotificationCount'>{$contributor['contributions']}</span>
						</span>
					</li>
				{{endforeach}}
			</ul>
		</div>
	{{endif}}
</div>