<ips:template parameters="$table, $used, $count" />
<h1 class="ipsType_pageTitle ipsPageHeader">{lang="my_attachments"}</h1>

{{if member.group['g_attach_max'] > 0}}
	{{$percentage = round( ( $used / ( \IPS\Member::loggedIn()->group['g_attach_max'] * 1024 ) ) * 100 );}}
	<div class='ipsBox ipsfocus_reset'>
		{theme="ipsfocus_b1"}<h2 class='ipsType_minorHeading'>{lang="my_attachment_quota"}</h2>{theme="ipsfocus_b2"}
		<div class='ipsProgressBar ipsProgressBar_fullWidth ipsClear {{if $percentage >= 90}}ipsProgressBar_warning{{endif}}' >
			<div class='ipsProgressBar_progress' style="width: {$percentage}%">
				<span data-role="percentage">{$percentage}</span>%
			</div>
		</div>
		<br>
		<p class='ipsType_reset ipsType_center'>
			{lang="my_attachments_blurb" sprintf="\IPS\Output\Plugin\Filesize::humanReadableFilesize( $used ), \IPS\Output\Plugin\Filesize::humanReadableFilesize( \IPS\Member::loggedIn()->group['g_attach_max'] * 1024 )"}
		</p>
      {theme="ipsfocus_b3"}
	</div>
<br />
{{endif}}

<div class='ipsBox ipsfocus_reset' data-controller="core.front.attachments.list">
	{theme="ipsfocus_b1"}<h2 class='ipsType_sectionTitle ipsType_medium ipsType_reset'>{lang="my_attachments_count" pluralize="$count"}</h2>{theme="ipsfocus_b2"}
	{$table|raw}
  {theme="ipsfocus_b3"}
</div>