<ips:template parameters="$stream, $html, $hasForm, $rssLink=NULL, $canCopy" />
<section data-controller='core.front.streams.main' data-streamID='{{if isset( \IPS\Request::i()->id )}}{expression="\IPS\Request::i()->id"}{{else}}all{{endif}}'>	
	<div class="ipsPageHeader streamPageHeader ipsClearfix ipsSpacer_bottom">
		<h1 class='ipsType_pageTitle' data-role='streamTitle'>
			{$stream->_title}
			{{if \IPS\Member::loggedIn()->member_id}}
				<a data-action="toggleStreamDefault" data-change="1" href="{$stream->url()->setQueryString('default', 1)}" data-ipsTooltip title='{lang="stream_this_isnt_default"}' class='ipsBadge ipsBadge_icon ipsBadge_small ipsType_middle ipsBadge_neutral ipsFaded ipsFaded_more {{if \IPS\Member::loggedIn()->defaultStream === $stream->_id}}ipsHide{{endif}}'><i class='fa fa-check'></i></a>
				<a data-action="toggleStreamDefault" data-change="0" href="{$stream->url()->setQueryString('default', 0)}" data-ipsTooltip title='{lang="stream_this_is_default"}' class='ipsBadge ipsBadge_icon ipsBadge_small ipsType_middle ipsBadge_positive {{if \IPS\Member::loggedIn()->defaultStream !== $stream->_id}}ipsHide{{endif}}'><i class='fa fa-check'></i></a>
			{{endif}}
		</h1>

		{{if $rssLink || ( $stream->member && $stream->member == \IPS\Member::loggedIn()->member_id )}}
			<ul class="ipsList_inline ipsPos_right ipsType_blendLinks ipsResponsive_hidePhone">
				{{if $rssLink}}	
					<li><a href="{$rssLink}"><i class="fa fa-rss"></i> {lang="rss"}</a></li>
				{{endif}}
				{{if $stream->member && $stream->member == \IPS\Member::loggedIn()->member_id}}
					<li>
						<a href='{$stream->url()}' title='{lang="stream_share_desc"}' data-ipsMenu data-ipsTooltip id='elStreamShare'><i class='fa fa-share-alt'></i> {lang="stream_share"}</a>
						<div class='ipsMenu ipsMenu_wide ipsPad ipsHide' id='elStreamShare_menu'>
							<h2 class='ipsType_sectionHead'>{lang="share_stream_title"}</h2>
							<hr class='ipsHr'>
							<p class='ipsType_medium'>
								{lang="share_stream_info"}
							</p>
							<input type='text' value='{$stream->url()}' class='ipsField_fullWidth'>
						</div>
					</li>
				{{endif}}
			</ul>
		{{endif}}

		{{if $hasForm}}
			<p class='ipsType_reset ipsType_normal ipsSpacer_bottom ipsCursor_pointer' data-role='streamOverview'>
				<span data-role='streamBlurb'>{$stream->blurb()}</span> <a href='#' data-streamID="{$stream->_id}" data-action='editStream'>{lang="stream_edit_feed"} <i class='fa fa-caret-down'></i></a>
			</p>
		
			<div data-role='filterForm' class='ipsJS_hide ipsSpacer_top'>
				<div data-role="filterFormLoading" class="cStreamForm_loading ipsAreaBackground ipsPad ipsHide">
					<div class="ipsAreaBackground_reset">
						<div class="ipsLoading"></div>
					</div>
				</div>
			</div>
		{{elseif $canCopy}}
			<p class='ipsType_reset ipsType_normal ipsSpacer_bottom ipsCursor_pointer' data-role='streamOverview'>
				<span data-role='streamBlurb'>{$stream->blurb()}</span>
			</p>
			{{$owner = \IPS\Member::load( $stream->member );}}

			<div class='ipsAreaBackground ipsPad ipsPhotoPanel ipsPhotoPanel_mini ipsClearfix'>
				{template="userPhoto" group="global" app="core" params="$owner, 'mini'"}
				<div>
					<a href='{$stream->url()->setQueryString('do', 'copy')}' class='ipsButton ipsButton_primary ipsButton_large ipsPos_right ipsResponsive_noFloat'><i class='fa fa-plus'></i> &nbsp;{lang="stream_copy_feed"}</i></a>
					<p class='ipsType_reset ipsType_normal'>
						<strong>{lang="stream_copy_title" sprintf="$owner->name"}</strong><br>
						{lang="stream_copy_desc"}
					</p>
				</div>
			</div>
		{{endif}}
	</div>
	
	<div data-role='streamBody'>
		{$html|raw}
	</div>

	{{if $rssLink || ( $stream->member && $stream->member == \IPS\Member::loggedIn()->member_id )}}
		<ul class="ipsList_inline ipsType_blendLinks ipsSpacer_both ipsType_center ipsResponsive_showPhone ipsResponsive_block">
			{{if $rssLink}}	
				<li><a href="{$rssLink}"><i class="fa fa-rss"></i> {lang="rss"}</a></li>
			{{endif}}
			{{if $stream->member && $stream->member == \IPS\Member::loggedIn()->member_id}}
				<li>
					<a href='{$stream->url()}' title='{lang="stream_share_desc"}' data-ipsMenu data-ipsTooltip id='elStreamShare'><i class='fa fa-share-alt'></i> {lang="stream_share"}</a>
					<div class='ipsMenu ipsMenu_wide ipsPad ipsHide' id='elStreamShare_menu'>
						<h2 class='ipsType_sectionHead'>{lang="share_stream_title"}</h2>
						<hr class='ipsHr'>
						<p class='ipsType_medium'>
							{lang="share_stream_info"}
						</p>
						<input type='text' value='{$stream->url()}' class='ipsField_fullWidth'>
					</div>
				</li>
			{{endif}}
		</ul>
	{{endif}}
</section>