<ips:template parameters="$indexData, $nextOccurance, $startDate, $endDate, $allDay, $reviewRating, $condensed" />
{{if $condensed}}
	<time datetime='{$nextOccurance->mysqlDatetime()}' class='ipsCalendarDate ipsCalendarDate_small ipsPos_left'>
		<span class='ipsCalendarDate_month'>{$nextOccurance->monthNameShort}</span>
		<span class='ipsCalendarDate_date'>{$nextOccurance->mday}</span>
	</time>
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_noSpacing'>
		<div class='ipsColumn ipsColumn_narrow'>
			<time datetime='{$nextOccurance->mysqlDatetime()}' class='ipsCalendarDate ipsCalendarDate_large ipsPos_center'>
				<span class='ipsCalendarDate_month'>{$nextOccurance->monthNameShort}</span>
				<span class='ipsCalendarDate_date'>{$nextOccurance->mday}</span>
			</time>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<div class='ipsStream_comment ipsPad'>
				<p class='ipsType_reset ipsType_normal'>
					<strong class='ipsType_normal'>
						<time itemprop='startDate' content='{expression="$startDate->format( 'Y-m-d' )"}'>
							{$startDate->dayName} {$startDate->mday} {$startDate->monthName} {$startDate->year}{{if !$allDay}}, {$startDate->localeTime( FALSE )}{{endif}}
						</time>
						{{if $endDate}}
							{lang="until_lc"}
							<time itemprop='endDate' content='{expression="$endDate->format( 'Y-m-d' )"}'>
								{$endDate->dayName} {$endDate->mday} {$endDate->monthName} {$endDate->year}{{if !$allDay}}, {$endDate->localeTime( FALSE )}{{endif}}
							</time>
						{{endif}}
					</strong>
				</p>
				{{if $reviewRating !== NULL}}
					{template="rating" app="core" params="'medium', $reviewRating" group="global"}
				{{endif}}
				{{if trim( $indexData['index_content'] ) !== ''}}
					<div class='ipsType_richText ipsType_break ipsType_medium ipsSpacer_top ipsSpacer_half' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines'{{else}}data-searchable data-findTerm{{endif}}>
						{$indexData['index_content']|raw}
					</div>
				{{endif}}
			</div>
		</div>
	</div>
{{endif}}