<ips:template parameters="$image" />

<div class='ipsEmbedded ipsEmbedded_withImage'>
	<div class='ipsEmbedded_headerArea'>
		<h4 class='ipsType_reset ipsType_normal ipsTruncate ipsTruncate_line'><i class='fa fa-camera' data-ipsTooltip title='{lang="embed_gallery_image"}'></i> &nbsp;<a href='{$image->url()->setQueryString( 'do', ( \IPS\Request::i()->embedDo != 'findComment' ) ? \IPS\Request::i()->embedDo : null )}' title='{lang="view_this" sprintf="$image->caption"}' target='_top'>{$image->caption}</a></h4>
	</div>
	<div class='ipsEmbedded_content'>
		<div class='ipsPhotoPanel ipsPhotoPanel_tiny ipsClearfix ipsType_medium'>
			{template="userPhoto" group="global" app="core" params="$image->author(), 'tiny'"}
			<div>
				{lang="byline_nodate" htmlsprintf="$image->author()->link()"}<br>
				<span class='ipsType_small'>{lang="in"} {$image->directContainer()->_title}, <span class='ipsType_light'>{datetime="$image->date"}</span>
			</div>
		</div>
		<ul class='ipsList_inline ipsType_small ipsEmbedded_stats'>
			{{if $image->container()->allow_rating}}
				<li>{template="rating" app="core" params="'small', $image->averageRating()" group="global"}</li>
			{{endif}}
			{{if $image->directContainer()->allow_comments}}
				<li><i class='fa fa-comment'></i> {lang="num_comments" pluralize="$image->comments"}</li>
			{{endif}}
		</ul>
	</div>
	<div style='background-image: url( {file="$image->thumb_file_name" extension="gallery_Images"} );' class='ipsEmbedded_image cGalleryTrimmedImage'>
		<a href='{$image->url()}' target='_top'>
			<img src='{file="$image->thumb_file_name" extension="gallery_Images"}'>
		</a>
	</div>
</div>