<ips:template parameters="$cards" />

<a href='{url="app=nexus&module=clients&controller=cards&do=add" seoTemplate="clientscards"}' class='ipsPos_right ipsButton ipsButton_important ipsButton_verySmall' title="{lang="cards_add_title"}">{lang="cards_add"}</a>
<h1 class='ipsType_pageTitle'>{lang="cards_title"}</h1>

<p class='ipsType_normal'>
	{lang="cards_info"}
</p>

<ul class='ipsList_inline cNexusCards ipsSpacer_top'>
	{{foreach $cards as $card}}
		<li>
			<span class='cNexusCards_number'>
				{{if $card['card_type'] == 'american_express' OR $card['card_type'] == 'diners_club'}}
					XXXX XXXXXX X{$card['card_number']}
				{{else}}
					XXXX XXXX XXXX {$card['card_number']}
				{{endif}}
			</span>
			{{if $card['card_type']}}
				<span class='cNexusCards_type cPayment cPayment_{$card['card_type']}'>{lang="card_type_{$card['card_type']}"}</span>
			{{endif}}
			{{if $card['card_expire']}}
				<span class='cNexusCards_expTitle'>{lang="cards_exp"}</span>
				<span class='cNexusCards_exp'>{$card['card_expire']}</span>
			{{endif}}
			
			<a href="{url="app=nexus&module=clients&controller=cards&do=delete&id={$card['id']}" seoTemplate="clientscards" csrf="true"}" class='cNexusCards_delete' data-confirm data-ipsTooltip title='{lang="delete_this_card"}'>&times;</a>
		</li>
	{{endforeach}}
</ul>