<ips:template parameters="$currentCategory=NULL" />
{{$categories = $currentCategory ? $currentCategory->children() : \IPS\downloads\Category::roots();}}
<div id='elDownloadsCategories' class='ipsWidget ipsWidget_vertical ipsBox'>
	<h3 class='ipsType_sectionTitle ipsType_reset'>{{if $currentCategory}}{lang="subcategories"}{{else}}{lang="categories"}{{endif}}</h3>
	<div class='ipsPad_half'>
		<div class='ipsSideMenu'>
			<ul class='ipsSideMenu_list'>
				{{foreach $categories as $category}}
					{{if $category->open OR \IPS\Member::loggedIn()->isAdmin()}}
						<li>
							<a href="{$category->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><span class='ipsBadge ipsBadge_style1 ipsPos_right cDownloadsCategoryCount'>{number="\IPS\downloads\File::contentCount( $category )"}</span><strong class='ipsType_normal'>{$category->_title}</strong></a>
							{{if $category->hasChildren()}}
								<ul class="ipsSideMenu_list">
									{{foreach $category->children() as $idx => $subcategory}}
										{{if $subcategory->open OR \IPS\Member::loggedIn()->isAdmin()}}
											<li>
												{{if $idx >= 5}}
													<a href='{$category->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" sprintf="count( $category->children() ) - 5"}</span></a>
													{{break;}}
												{{else}}
													<a href="{$subcategory->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><strong class='ipsPos_right ipsType_small cDownloadsCategoryCount'>{number="\IPS\downloads\File::contentCount( $subcategory )"}</strong>{$subcategory->_title}</a>
												{{endif}}
											</li>
										{{endif}}
									{{endforeach}}
								</ul>
							{{endif}}
						</li>
					{{endif}}
				{{endforeach}}
			</ul>
			<p class='ipsType_center'>
				<a href='{url="app=downloads&module=downloads&controller=browse&do=categories" seoTemplate="downloads_categories"}' class=''>{lang="browse_categories_d"} &nbsp;<i class='fa fa-caret-right'></i></a>
			</p>
		</div>
		{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
			{template="chooseCurrency" app="nexus" group="store" params="$currentCategory ? $currentCategory->url() : \IPS\Http\Url::internal('app=downloads&module=downloads&controller=browse', 'front', 'downloads')"}
		{{endif}}
	</div>
</div>