<ips:template parameters="$select, $pagination, $members" />

{{if trim( $pagination )}}
	{$pagination|raw}
	<br><br>
{{endif}}

{{if count( $select )}}
	<table class="ipsTable ipsTable_zebra">
		<thead>
			<tr>
				<th>{lang="member"}</th>
				<th>{lang="gallery_images"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $select as $row}}
				{{if isset( $members[ $row['image_member_id'] ] )}}
					{{$member = \IPS\Member::constructFromData( $members[ $row['image_member_id'] ] );}}
				{{else}}
					{{$member = new \IPS\Member;}}
				{{endif}}
				<tr>
					<td>{template="userPhoto" app="core" group="global" params="$member"} {$member->name}</td>
					<td><a href='{$member->url()->setQueryString( array( 'do' => 'content', 'type' => 'gallery_image' ) )}' target='_blank'>{$row['images']}</a></td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>
	<br>

	{$pagination|raw}
{{else}}
	<p class="ipsPad">{lang="no_results"}</p>
{{endif}}