<?php

$lang = array(
'guest_buttonBar'		=> 'Button bar background (for Alert)',
'customLogoText'		=> 'Text Logo (if empty, site name is used)',
'ipsf_guestStyle'		=> 'Guest message style',
'ipsf_guestText'		=> 'Guest message',
'guest_titleColor'		=> 'Title bar text color (for Alert)',
'guest_titleBackground'		=> 'Title bar background (for Alert)',
'ipsf_guest'		=> 'Enable guest message?',
'ipsf_socialButton'		=> 'Social button type',
'guest_textColor'		=> 'Message text color (for Alert)',
'theme_custom_tab_guestmessage'		=> '<i class="fa fa-user-plus"></i> Guest Message',
'guest_background'		=> 'Box background color (for Alert)',
'ipsf_socialContent'		=> 'Social buttons (HTML)',
'ipsf_backgroundType'		=> 'Background type',
'ipsf_subforumNum'		=> 'Number of subforum columns',
'ipsf_social'		=> 'Enable social media buttons?',
'ipsf_videoRgb'		=> 'Video: background color (r,g,b)',
'ipsf_videoID'		=> 'Video: ID (Youtube)',
'ipsf_videoPosition'		=> 'Video: position',
'ipsf_videoOverlay'		=> 'Video: overlay color (rgba)',
'ipsf_fixedWidth'		=> 'Fixed width (px)',
'theme_custom_tab_ipsfmisc'		=> '<i class="fa fa-info-circle"></i> Miscellaneous',
'ipsf_postDateBar'		=> 'Post block header bar',
'ipsf_postButtons'		=> 'Post buttons in topic view',
'ipsf_topicListStats'		=> 'Dual column for topic list stats',
'ipsf_grayscale'		=> 'Greyscale effect for no new content?',
'ipsf_ficonFontR'		=> 'Icon font-size (responsive, px)',
'theme_custom_tab_ipsfsocial'		=> '<i class="fa fa-facebook-square"></i> Social Buttons',
'ipsf_ficonHeightR'		=> 'Icon height (responsive, px)',
'ipsf_ficonWidthR'		=> 'Icon width (responsive, px)',
'ipsf_ficonRadius'		=> 'Icon radius (px)',
'theme_custom_tab_ipsfvideotab'		=> '<i class="fa fa-video-camera"></i> Video Background',
'ipsf_ficonWidth'		=> 'Icon width (px)',
'ipsf_ficonFont'		=> 'Icon font-size (px)',
'ipsf_subforumColumns'		=> 'Place subforums into columns',
'ipsf_navIcons'		=> 'Show navigation icons?',
'ipsf_postSize'		=> 'Font size for posts (px)',
'ipsf_ficonHeight'		=> 'Icon height (px)',
'theme_custom_tab_ipsfsettings'		=> '<i class="fa fa-globe"></i> Holidays',
'ipsf_ficonColor'		=> 'Icon color',
'theme_custom_tab_ipsfficontab'		=> '<i class="fa fa-comments"></i> Forum Icons',
'ipsf_inputBorder'		=> 'Input border',
'ipsf_ficonTransparent'		=> 'Transparent background?',
'ipsf_inputText'		=> 'Input text',
'theme_custom_tab_ipsfheader'		=> '<i class="fa fa-bars"></i> Header',
'ipsf_ficonBackground'		=> 'Icon background',
'theme_custom_tab_ipsfinputtab'		=> '<i class="fa fa-keyboard-o"></i> Forms',
'ipsf_inputBackgroundF'		=> 'Input background (focus)',
'ipsf_commentHeaderBar'		=> 'Post header bar',
'ipsf_inputBackground'		=> 'Input background',
'ipsf_headerScripts'		=> 'Header scripts : &lt;link&gt;, &lt;script&gt;, etc',
'ipsf_inputBorderF'		=> 'Input border (focus)',
'ipsf_popupText'		=> 'Popup text',
'ipsf_editorBorder'		=> 'Editor border',
'ipsf_commentControls'		=> 'Post buttons bar',
'ipsf_tags'		=> 'Tags',
'ipsf_footer'		=> 'Footer text',
'ipsf_tagsHover'		=> 'Tag hover',
'singleNavigationBar'		=> 'Single Navigation Bar?',
'ipsf_newBadge'		=> 'NEW badge',
'ipsf_maintitleText'		=> 'Maintitle text',
'theme_custom_tab_topicview'		=> '<i class="fa fa-th-list"></i> Topic View',
'ipsf_widgetBorder'		=> 'Widget border color',
'ipsf_maintitle'		=> 'Maintitle',
'ipsf_borderColor'		=> 'ipsBox border color',
'ipsf_popupMenu'		=> 'Popup menu',
'ipsf_contentWrap'		=> 'Content background',
'theme_custom_tab_globalmessagetab'		=> '<i class="fa fa-align-left"></i> Global Message',
'socialHeight'		=> 'Social buttons height (px)',
'ifBg3_image'		=> 'Background #3 image',
'topicButtonStyle'		=> 'Topic button style',
'ifBg4_image'		=> 'Background #4 image',
'ifBg1_image'		=> 'Background #1 image',
'ifBg2_image'		=> 'Background #2 image',
'backgroundQuantity'		=> 'Display how many images?',
'pickerGroups'		=> 'Limit picker to groups? (comma separate id\'s)',
'breadcrumbHeight'		=> 'Breadcrumb height (px)',
'simpleTopicLayout'		=> '"Separated" topic layout?',
'responsiveLogo'		=> 'Logo font size (responsive, px)',
'ficonImageRead'		=> 'Image icon (read)',
'ipsf_footerOne'		=> 'Footer column 1',
'ipsf_footerMobile'		=> 'Show footer on mobiles and tablets?',
'ipsf_footerThree'		=> 'Footer column 3',
'ipsf_footerTwo'		=> 'Footer column 2',
'ipsf_footerSix'		=> 'Footer column 6',
'ficonImageUnread'		=> 'Image icon (unread)',
'ipsf_footerFive'		=> 'Footer column 5',
'ipsf_footerFour'		=> 'Footer column 4',
'ipsf_megaFooter'		=> 'Show mega footer?',
'ipsf_footerColumns'		=> 'How many columns?',
'theme_custom_tab_ipsfmegafooter'		=> '<i class="fa fa-columns"></i> Mega Footer',
'ipsf_ficonRead'		=> '"Read" icon (Font Awesome Unicode)',
'ipsf_commentHeaderText'		=> 'Comment header text',
'ipsf_countdownDate'		=> 'Countdown date (YYYY/MM/DD HH:MM:SS)',
'ipsf_lightButtonBar'		=> 'Subtle pagination bar?',
'ipsf_countdownText'		=> 'Countdown text',
'ipsf_postAuthorBar'		=> 'Post block author bar',
'ipsf_countdown'		=> 'Countdown',
'ipsf_christmas'		=> 'Christmas',
'ipsf_ficonUnread'		=> '"Unread" icon (Font Awesome Unicode)',
'ipsf_pickerMobile'		=> 'Enable picker on tablets and mobiles?',
'ipsf_horizontalTopic'		=> 'Horizontal topic layout?',
'ipsfocus_reset'		=> 'ipsfocus_reset',
'ipsfocus_b3'		=> 'IPSFocus box 3',
'ipsf_valentines'		=> 'Valentines Day',
'ipsfocus_b2'		=> 'IPSFocus box 2',
'ifBg_cookiePrefix'		=> 'IPSFocus cookie prefix',
'ipsf_guestPicker'		=> 'Show picker to guests?',
'theme_custom_tab_ipsfocusdev'		=> '<i class="fa fa-exclamation-triangle"></i> IPSFocus Development',
'ifBg4_attachment'		=> 'Background #4 attachment',
'ipsfocus_b1'		=> 'IPSFocus box 1',
'ifBg4_size'		=> 'Background #4 size',
'ifBg4_repeat'		=> 'Background #4 repeat',
'ifBg4_position'		=> 'Background #4 position',
'ifBg3_position'		=> 'Background #3 position',
'ifBg4_hex'		=> 'Background #4 hex',
'ifBg2_repeat'		=> 'Background #2 repeat',
'ifBg3_attachment'		=> 'Background #3 attachment',
'ifBg3_size'		=> 'Background #3 size',
'ifBg3_repeat'		=> 'Background #3 repeat',
'ifBg2_attachment'		=> 'Background #2 attachment',
'ifBg3_hex'		=> 'Background #3 hex',
'ifBg2_size'		=> 'Background #2 size',
'ifBg2_position'		=> 'Background #2 position',
'ifBg2_hex'		=> 'Background #2 hex',
'ifBg1_attachment'		=> 'Background #1 attachment',
'ifBg1_size'		=> 'Background #1 size',
'ifBg1_position'		=> 'Background #1 position',
'ifBg1_repeat'		=> 'Background #1 repeat',
'theme_custom_tab_ipsfpickertab'		=> '<i class="fa fa-picture-o"></i> Background Picker',
'ipsf_fixedHeader'		=> 'Fixed header?',
'ipsf_pickerDefault'		=> 'Default background',
'ipsf_indexNew'		=> 'Show NEW badge on index?',
'ifBg1_hex'		=> 'Background #1 hex',
'ipsf_searchHeight'		=> 'Height of search bar (px)',
'theme_custom_tab_ipsfbreadcrumbtab'		=> '<i class="fa fa-caret-right"></i> Breadcrumb',
'ipsf_userNavHeight'		=> 'Height of user navigation (px)',
'ipsf_bc_link'		=> 'Breadcrumb link color',
'ipsf_bc_background'		=> 'Breadcrumb background',
'ipsf_bc_styles'		=> 'Additional breadcrumb styles',
'ipsf_advancedBreadcrumb'		=> 'Advanced (arrow image) Breadcrumb?',
'ipsf_bc_text'		=> 'Breadcrumb text color',
'ipsf_widgetText'		=> 'Widget header text',
'ipsf_logoSize'		=> 'Logo font size (px)',
'ipsf_logoHeight'		=> 'Logo height (px)',
'ipsf_mobileTextLogo'		=> 'Force text logo on mobiles?',
'ipsf_logoHeightR'		=> 'Logo height (responsive, px)',
'ipsf_sloganColor'		=> 'Slogan text color',
'ipsf_textLogoImage'		=> 'Show mini logo next to text?',
'ipsf_logoColor'		=> 'Logo text color',
'ipsf_guestMobile'		=> 'Show guest message on mobiles?',
'ipsf_slogan'		=> 'Logo slogan (leave empty to disable)',
);
