<ips:template parameters="$indexData, $itemData, $albumData, $image, $url, $condensed" />
{{if $condensed}}
	{{if $image}}
		<span class='ipsThumb_bg ipsThumb_small ipsPos_left' style='background-image: url("{file="$image" extension="gallery_Images"}")'>
			<img src='{file="$image" extension="gallery_Images"}' alt='' class="">
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_wide ipsType_center'>
			<a href='{$url}' title='{lang="view_this_image" sprintf="$indexData['index_title']"}'>
				{{if $image}}
					<img src='{file="$image" extension="gallery_Images"}' alt='' class="ipsImage ipsStream_thumbnail">
				{{else}}
					<div class='ipsNoThumb'></div>
				{{endif}}
			</a>
		</div>
		<div class='ipsColumn ipsColumn_fluid ipsStream_snippetInfo'>
			{{if $albumData}}
				<p class='ipsType_reset ipsType_normal ipsType_light ipsSpacer_bottom ipsSpacer_half'>
					{lang="from_the_album"} <a href='{url="app=gallery&module=gallery&controller=browse&album={$albumData['album_id']}" seoTemplate="gallery_album" seoTitle="$albumData['album_name_seo']"}'>{$albumData['album_name']}</a>
				</p>
			{{endif}}
			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='3 lines'{{else}}data-searchable data-findTerm{{endif}}>
					{$indexData['index_content']|raw}
				</div>
			{{endif}}

			{{if $itemData['image_copyright']}}
				<p class='ipsSpacer_top ipsType_light ipsType_medium ipsType_reset'>
					&copy; {$itemData['image_copyright']}
				</p>
			{{endif}}
		</div>
	</div>
{{endif}}