<ips:template parameters="$page, $widgets" original_group="page_builder" key="page_page_builder_two_columns" />
<div>
	<div class='ipsGrid ipsGrid_collapsePhone'>
		<div class='ipsGrid_span6'>
			{template="widgetContainer" group="pages" app="cms" params="'col1', $widgets, 'horizontal'"}
		</div>
		<div class='ipsGrid_span6'>
			{template="widgetContainer" group="pages" app="cms" params="'col2', $widgets, 'horizontal'"}
		</div>
	</div>
</div>