<ips:template parameters="$transaction, $log" />

<li class='ipsClearfix cTransaction_positive'>
	<div class='cTransaction_icon ipsPos_left'>
		<i class='fa fa-check'></i>
	</div>
	<div class='cTransaction_info ipsType_normal'>
		<h3 class="ipsType_sectionHead">
			<strong>
				{{if $transaction->method === 0}}
					{{if $transaction->gw_id}}
						{lang="tstatus_okay_set"}
					{{else}}
						{lang="tstatus_okay_credit"}
					{{endif}}
				{{else}}
					{lang="tstatus_okay_set"}
				{{endif}}
			</strong>
		</h3>
		
		{{if isset( $log['on'] ) and $log['on']}}
			{expression="\IPS\DateTime::ts( $log['on'] )"}
			{{if isset( $log['by'] ) and $log['by']}}
				<br>
				<span class='ipsType_medium ipsType_light'>
					{lang="byline_nodate" sprintf="\IPS\Member::load( $log['by'] )->name"}
				</span>
			{{endif}}
		{{else}}
			<br>
			{lang="tstatus_okay_desc"}
		{{endif}}
	</div>
</li>