<ips:template parameters="$table, $headers, $albums" />
{{foreach $albums as $album}}
	<li class='ipsDataItem ipsAreaBackground_reset'>
		<div class='ipsColumns ipsColumns_collapsePhone'>
			<div class='ipsColumn ipsColumn_wide'>
				<div class='ipsPad'>
					<h3 class='ipsType_sectionHead'>
						{{if \IPS\gallery\Image::containerUnread( $album )}}
							<span class="ipsItemStatus" data-ipsTooltip title="{lang="album_new_content"}">
								<i class="fa fa-circle"></i>
							</span>
						{{endif}}
						{{if \IPS\gallery\Image::containerUnread( $album )}}<strong>{{endif}}
							<div class='ipsContained ipsType_break'><a href='{$album->url()}' title='{lang="view_this_album" sprintf="$album->_title"}'>{$album->_title}</a></div>
						{{if \IPS\gallery\Image::containerUnread( $album )}}</strong>{{endif}}
					</h3>
					{{if $album->last_img_date}}<p class='ipsType_light ipsType_medium ipsType_reset'>{lang="updated"} {datetime="$album->last_img_date"}</p>{{endif}}
					<ul class='ipsList_inline ipsType_medium'>
						<li><i class='fa fa-camera'></i> {lang="num_images" pluralize="$album->count_imgs"}</li>
						{{if $album->allow_comments}}
							<li><i class='fa fa-comment'></i> {lang="num_comments" pluralize="$album->count_comments"}</li>
						{{endif}}
					</ul>
					<div class='ipsType_medium ipsType_richText ipsSpacer_both ipsContained' data-ipsTruncate data-ipsTruncate-size='3 lines' data-ipsTruncate-type='remove'>
						{$album->truncated()|raw}
					</div>
					{{if !isset( \IPS\Request::i()->tab ) || \IPS\Request::i()->tab !== 'node_gallery_gallery'}}
						<div class='ipsPhotoPanel ipsPhotoPanel_tiny'>
							{template="userPhoto" group="global" app="core" params="$album->owner(), 'tiny'"}
							<div>
								<span class='ipsType_minorHeading'>{lang="album_created_by"}</span><br>
								<span class='ipsType_normal'>{$album->owner()->link()|raw}</span>
							</div>
						</div>
					{{endif}}
				</div>
			</div>
			<div class='ipsColumn ipsColumn_fluid'>
				{{if $table->canModerate()}}
					<div class='ipsPos_right ipsPad'>
						<input type='checkbox' data-role='moderation' name="moderate[{$album->_id}]" data-actions="{expression="implode( ' ', $table->multimodActions( $album ) )"}" data-state=''>
					</div>
				{{endif}}
				<div class='ipsPad cGalleryAlbums_recent'>
					<ul class='ipsList_reset'>
						<li {{if $album->coverPhoto( 'small' )}}style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $album->coverPhoto( 'small' ) )"}" );'{{endif}} class='cGalleryTrimmedImage'>
							<a href='{$album->url()}' title='{lang="view_this_album" sprintf="$album->_title"}'>
								{{if $album->coverPhoto( 'small' )}}
									<img src='{$album->coverPhoto( 'small' )}' alt='{$album->_title}'>
								{{endif}}
							</a>
						</li>
						{{foreach $album->_latestImages as $image }}
							<li style='background-image: url( "{file="$image->thumb_file_name" extension="gallery_Images"}" );' class='cGalleryTrimmedImage'>
								<a href='{$image->url()}'>
									<img src='{file="$image->thumb_file_name" extension="gallery_Images"}' alt="{$image->caption}">
									{{if ( $image->directContainer()->allow_comments && $image->container()->allow_comments )}}
										<span class='cGalleryAlbums_comments'><i class='fa fa-comment'></i> {expression="count( $image->comments() )"}</span>
									{{endif}}
								</a>
							</li>
						{{endforeach}}
					</ul>	
				</div>			
			</div>
		</div>
	</li>
{{endforeach}}