<ips:template parameters="$invoice, $summary, $address" />
<div class="ipsPrint">
	{setting="nexus_invoice_header"}
	<h1>{lang="invoice_number" sprintf="$invoice->id"}</h1>
	<div class="ipsClearfix ipsSpacer_bottom">
		<div class="ipsPos_left">
			<br>
			{{if $invoice->po}}
				{lang="invoice_po_number"}: {$invoice->po}<br>
				<br>
			{{endif}}
			{{if $invoice->member->member_id}}
				{$invoice->member->cm_name}
			{{else}}
				{$invoice->guest_data['member']['name']}
			{{endif}}
			<br>
			{{if $address}}{$address->toString('<br>')|raw}{{endif}}
		</div>
		<div class="ipsPos_right">
			<strong>{setting="board_name"}</strong><br>
			{expression="\IPS\GeoLocation::buildFromJson( \IPS\Settings::i()->site_address )->toString('<br>')" raw="true"}<br>
			<br>
			{$invoice->date->format( 'd F Y' )}
		</div>
	</div>
	{{if $invoice->notes}}
		<div class="ipsSpacer_bottom">{$invoice->notes}</div>
	{{endif}}
	<table>
		<thead>
			<tr>
				<th>{lang="invoice_item"}</th>
				<th>{lang="invoice_unit_price"}</th>
				<th>{lang="invoice_quantity"}</th>
				<th>{lang="invoice_line_price"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $summary['items'] as $k => $item}}
				<tr>
					<td>{$item->name}</td>
					<td>{$item->price}</td>
					<td>{$item->quantity}</td>
					<td>{$item->linePrice()}</td>
				</tr>
			{{endforeach}}
		</tbody>
		<tfoot>
			<tr>
				<td colspan="3"><strong>{lang="subtotal"}</strong></td>
				<td><strong>{$summary['subtotal']}</strong></td>
			</tr>
			{{foreach $summary['shipping'] as $shipping}}
				<tr>
					<td colspan="3">{$shipping->name}</td>
					<td>{$shipping->linePrice()}</td>
				</tr>
			{{endforeach}}
			{{foreach $summary['tax'] as $tax}}
				<tr>
					<td colspan="3">{$tax['name']} ({expression="$tax['rate']*100"}%)</td>
					<td>{$tax['amount']}</td>
				</tr>
			{{endforeach}}
			<tr class="ipsType_large">
				<td colspan="3"><strong>{lang="total"}</strong></td>
				<td><strong>{$summary['total']}</strong></td>
			</tr>
		</tfoot>
	</table>
	{setting="nexus_invoice_footer"}
</div>