<ips:template parameters="$input" />
<input
	name="{$input->name}"
	type="number"
	{{if $input->value === NULL}}
		value=""
		data-jsdisable="true"
	{{elseif is_numeric( $input->value )}}
		value="{expression="number_format( $input->value, $decimals === true ? mb_strlen( mb_substr( $input->value, mb_strpos( $input->value, '.' ) + 1 ) ) : $decimals, '.', '' )"}"
	{{else}}
		value="0"
	{{endif}}
	class="ipsField_tiny"
	min="0"
>
{lang="hours_ago"}
&nbsp;
<div class="ipsFieldRow_inlineCheckbox">
	{lang="or"}
	&nbsp;
	<span class='ipsCustomInput'>
		<input type="checkbox" role='checkbox' data-control="unlimited" name="{$input->name}_unlimited" id='{$input->name}_unlimited_check' value="1" {{if NULL === $input->value}}checked aria-checked='true'{{endif}} aria-labelledby='{$input->name}_unlimited_label'>
		<span></span>
	</span> <label for='{$input->name}_unlimited_check' id='{$input->name}_unlimited_label' class='ipsField_unlimited'>{lang="support_stream_any_time"}</label>
</div>
