<ips:template parameters="$comment, $entry" />

<div class='ipsDataList ipsAreaBackground_light ipsClearfix'>
	<div class='ipsDataItem'>
		<div class='ipsDataItem_icon'>
			{template="userPhoto" group="global" app="core" params="$entry->author()"}
		</div>
		<div class='ipsDataItem_main'>
			<h3 class='ipsType_sectionHead'>
				<a href='{$entry->url()}' title='{lang="view_this_entry" sprintf="$entry->mapped('title')"}'>
					{$entry->mapped('title')}
				</a>
			</h3>
			<p class='ipsType_normal ipsType_blendLinks ipsType_reset'>{lang="in"} <a href='{$entry->container()->url()}'>{$entry->container()->_title}</a></p>
			<p class='ipsType_normal ipsType_light ipsType_blendLinks ipsType_reset'>
				{{if $entry->container()->owner() instanceof \IPS\Member}}
					{lang="blog_by" htmlsprintf="$entry->container()->owner()->link()"}
				{{else}}
					<i class='fa fa-users'></i> {lang="group_blog_by" sprintf="\IPS\Member::loggedIn()->language()->addToStack( 'blogs_groupblog_name_' . $entry->container()->id )"}
				{{endif}}
			</p>
		</div>
	</div>
</div>