<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class='', $attributes=array(), $sidebar, $form=NULL" />
<form accept-charset='utf-8' class="ipsForm {$class}" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}} {{foreach $attributes as $k => $v}}{$k}="{$v}"{{endforeach}} data-ipsForm>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		{{if is_array($v)}}
			{{foreach $v as $_k => $_v}}
				<input type="hidden" name="{$k}[{$_k}]" value="{$_v}">
			{{endforeach}}
		{{else}}
			<input type="hidden" name="{$k}" value="{$v}">
		{{endif}}
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( uniqid() )"}">
	{{endif}}
	<ul class='ipsList_reset'>
		{{foreach $elements as $collection}}
			{{foreach $collection as $k => $input}}
				{{if mb_stripos( $k, 'image_credit_info' ) !== FALSE || mb_stripos( $k, 'image_copyright' ) !== FALSE}}
					<li class='ipsFieldRow ipsFieldRow_fullWidth ipsJS_hide' data-role='{expression="mb_stripos( $k, 'image_credit_info' ) !== FALSE ? 'image_credit_info' : 'image_copyright'"}'>
						<label class='ipsFieldRow_title'>{lang="$k"}</label>
						{$input->html()|raw}
					</li>
				{{elseif mb_stripos( $k, 'image_title' ) !== FALSE}}	
					<li class='ipsFieldRow ipsFieldRow_primary ipsFieldRow_fullWidth' data-role="captionRow">
						<label class='ipsFieldRow_title'>{lang="$k"}</label>
						{$input->html()|raw}
					</li>
				{{else}}
					{{if is_object( $input ) }}
						{$input->rowHtml($form)|raw}
					{{else}}
						{$input|raw}
					{{endif}}
				{{endif}}
			{{endforeach}}
		{{endforeach}}
	</ul>
	<ul class='ipsList_inline ipsSpacer_top ipsType_normal ipsJS_show'>
		<li><a href='#' data-action='addCopyright' data-opens='image_copyright'><i class='fa fa-plus'></i> {lang="add_copyright_image"}</a></li>
		<li><a href='#' data-action='addCredit' data-opens='image_credit_info'><i class='fa fa-plus'></i> {lang="add_credit_image"}</a></li>
	</ul>

	{{if $hiddenValues['edit'] != 0}}
		<button type='submit' data-role='saveAndDoPrev' class='cGallerySubmit_button cGallerySubmit_prevButton' name='submitButton' value='prev'><i class='fa fa-angle-left'></i></button>
	{{endif}}
	<button type='submit' data-role='saveAndDoNext' class='cGallerySubmit_button cGallerySubmit_nextButton' name='submitButton' value='next'><i class='fa fa-angle-right'></i></button>
</form>