<ips:template parameters="" />
<div class='ipsfocus_megaFooter colCount{theme="ipsf_footerColumns"}'>
	
	<div class='ipsLayout_container ipsClearfix'>
	
		<div class='footerCol'>
			{theme="ipsf_footerOne"}
		</div>
		
		{{if theme.ipsf_footerColumns > 1}}
		<div class='footerCol'>
			{theme="ipsf_footerTwo"}
		</div>
		{{endif}}
		
		{{if theme.ipsf_footerColumns > 2}}
		<div class='footerCol'>
			{theme="ipsf_footerThree"}
		</div>
		{{endif}}
		
		{{if theme.ipsf_footerColumns > 3}}
		<div class='footerCol'>
			{theme="ipsf_footerFour"}
		</div>
		{{endif}}
		
		{{if theme.ipsf_footerColumns > 4}}
		<div class='footerCol'>
			{theme="ipsf_footerFive"}
		</div>
		{{endif}}
		
		{{if theme.ipsf_footerColumns > 5}}
		<div class='footerCol'>
			{theme="ipsf_footerSix"}
		</div>
		{{endif}}
		
	</div>
	
</div>