<ips:template parameters="" />
<div class='ipsfocus_countdown'>
	<div class='title'>{theme="ipsf_countdownText"}</div>
	<div class='ipsfocus_timer'></div>
</div>

<script type='text/javascript'>
$(document).ready(function(){
	$('.ipsfocus_countdown .ipsfocus_timer').countdown('{theme="ipsf_countdownDate"}', function(event) {
		var ipsf_countdown = $(this).html(event.strftime(''
		+ '<span class="num">%w</span> <span class="dateType">weeks</span> '
		+ '<span class="num">%d</span> <span class="dateType">days</span> '
		+ '<span class="num">%H</span> <span class="dateType">hr</span> '
		+ '<span class="num">%M</span> <span class="dateType">min</span> '
		+ '<span class="num">%S</span> <span class="dateType">sec</span>'));
	});
});
</script>