<ips:template parameters="" />
<div id='ipsf_pickerWrap'>
	<div id='ipsf_picker' class='ipsClearfix'>
	    <span data-backgroundClass='ipsfocus_bg1' style='background-color: {theme="ifBg1_hex"}; background-image: url({resource="backgrounds/1.jpg" app="core" location="front"});'></span>
		<span data-backgroundClass='ipsfocus_bg2' style='background-color: {theme="ifBg2_hex"}; background-image: url({resource="backgrounds/2.jpg" app="core" location="front"});'></span>
    	<span data-backgroundClass='ipsfocus_bg3' style='background-color: {theme="ifBg3_hex"}; background-image: url({resource="backgrounds/3.jpg" app="core" location="front"});'></span>
	    <span data-backgroundClass='ipsfocus_bg4' style='background-color: {theme="ifBg4_hex"}; background-image: url({resource="backgrounds/4.jpg" app="core" location="front"});'></span>
	</div>
</div>