<ips:template parameters="$transaction, $log" />

<li class='ipsClearfix cTransaction_intermediate'>
	<div class='cTransaction_icon ipsPos_left'>
		<i class='fa fa-undo'></i>
	</div>
	<div class='cTransaction_info ipsType_normal'>
		<h3 class="ipsType_sectionHead">
			<strong>
				{lang="tstatus_rfnd_set"}
			</strong>
		</h3>
		<br>
		
		{{if isset( $log['to'] )}}
			<p class='ipsType_reset ipsType_medium'>
				{lang="transaction_refund_method"} {{if $log['to'] === 'gateway'}}{$transaction->method->_title}{{else}}{lang="refund_method_credit"}{{endif}}
				{{if isset( $log['ref'] ) and $log['ref']}}
					<br>{$log['ref']}
				{{endif}}
			</p>
		{{endif}}
		{{if isset( $log['on'] ) and $log['on']}}
			{expression="\IPS\DateTime::ts( $log['on'] )"}
			{{if isset( $log['by'] ) and $log['by']}}
				<br>
				<span class='ipsType_medium ipsType_light'>
					{lang="byline_nodate" sprintf="\IPS\Member::load( $log['by'] )->name"}
				</span>
			{{endif}}
		{{endif}}
	</div>
</li>