<ips:template parameters="$package, $hasCustomFields=FALSE" />

<li class='ipsDataItem' itemprop="itemListElement" itemscope="" itemtype="http://schema.org/Product">
	<div class='ipsDataItem_generic ipsDataItem_size5'>
		<a href='{$package->url()}' class='cNexusProduct_image'>
			{{if $package->image}}
				<img src="{$package->image}" class='ipsImage' itemprop="image">
			{{else}}
				<div class='ipsNoThumb ipsNoThumb_product'>&nbsp;</div>
			{{endif}}
		</a>
	</div>
	<div class='ipsDataItem_main'>
		<h2 class='ipsDataItem_title ipsType_sectionHead ipsType_blendLinks'>
			<a href="{$package->url()}" class='ipsTruncate ipsTruncate_line'>
				<span itemprop="name">{$package->_title}</span> {{if $package->featured}}<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_positive" data-ipsTooltip title='{lang="featured"}'><i class='fa fa-star'></i></span>{{endif}}
			</a>
		</h2>
		{{if $package->reviewable}}
			<div itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
				{template="rating" group="global" app="core" params="'large', $package->item()->averageReviewRating(), \IPS\Settings::i()->reviews_rating_out_of, $package->item()->memberReviewRating()"} <span class='ipsType_small'>({lang="num_reviews" pluralize="$package->item()->reviews"})</span>
				<meta itemprop="ratingValue" content="{$package->item()->averageReviewRating()}">
				<meta itemprop="reviewCount" content="{$package->item()->reviews}">
			</div>
		{{endif}}
		<div class='ipsType_richText ipsType_medium ipsType_break ipsContained ipsSpacer_top ipsSpacer_half' data-ipsTruncate data-ipsTruncate-size='4 lines' data-ipsTruncate-type='remove' itemprop="description">
			{$package->description|raw}
		</div>		
	</div>
	<div class='ipsDataItem_generic ipsDataItem_size5 ipsPos_top ipsType_right'>
		<div class='ipsPad_half' itemprop="offers" itemscope itemtype="http://schema.org/Offer">
			<span data-role="price">{$package->priceToDisplay()|raw}</span>

			{{if $package->physical}}
				{{if $package->stock !== 0}}
					<span class='ipsType_medium cNexusStock cNexusStock_inStock'>{{if settings.nexus_show_stock && $package->stock !== -1 && $package->stock !== -2}}{lang="x_in_stock" pluralize="$package->stock"}{{else}}{lang="in_stock"}{{endif}}</span>
					<link itemprop="availability" content='in_stock' href="http://schema.org/InStock">
				{{else}}
					<span class='ipsType_medium cNexusStock cNexusStock_notInStock ipsType_warning'>{lang="out_of_stock"}</span>
					<link itemprop="availability" content='out_of_stock' href="http://schema.org/OutOfStock">
				{{endif}}
			{{endif}}

			<br>
			{{if $package->stock === 0}}
				<span class='ipsButton ipsButton_primary ipsButton_verySmall ipsButton_narrow ipsButton_disabled ipsButton_noHover ipsCursor_locked'>{lang="out_of_stock"}</span>
			{{else}}
				<a href='{$package->url()->setQueryString( 'purchase', 1 )}' class='ipsButton ipsButton_primary ipsButton_verySmall ipsButton_narrow' data-ipsDialog data-ipsDialog-size='medium' data-ipsDialog-title='{lang="store_quick_view"}' data-ipsDialog-forceReload>
					<i class='fa fa-shopping-cart'></i>&nbsp;
					{{if $hasCustomFields}}
						{lang="add_and_choose_options"}
					{{else}}
						{lang="add_to_cart"}
					{{endif}}
				</a>
			{{endif}}
		</div>
	</div>
</li>