<ips:template parameters="$comment, $package, $item" />

<div class='ipsDataList ipsAreaBackground_light ipsClearfix'>
	<div class='ipsDataItem'>
		<div class='ipsDataItem_generic ipsDataItem_size2'>
			{template="thumbImage" group="global" app="core" params="$package->image, $package->_title, 'small', '', 'view_this', $package->url()"}
		</div>
		<div class='ipsDataItem_main'>
			<h3 class='ipsType_sectionHead'><a href="{$package->url()}" data-role='productLink' class='' itemprop="name">{$package->_title}</a></h3>
			<p class='ipsType_normal ipsType_light ipsType_blendLinks ipsType_reset'>{lang="in"} <a href='{$item->container()->url()}'>{$item->container()->_title}</a></p>
			<p class='ipsType_reset' itemprop="offers" itemscope itemtype="http://schema.org/Offer">
				<span data-role="price">{$package->priceToDisplay()|raw}</span>
			</p>
		</div>
	</div>
</div>