<ips:template parameters="$status" />
<span class="ipsBadge ipsBadge_style{{if $status == \IPS\nexus\Transaction::STATUS_PAID or $status == \IPS\nexus\Transaction::STATUS_PART_REFUNDED}}4{{elseif $status == \IPS\nexus\Transaction::STATUS_HELD}}1{{elseif $status == \IPS\nexus\Transaction::STATUS_REVIEW}}7{{elseif $status == \IPS\nexus\Transaction::STATUS_REFUSED}}5{{elseif $status == \IPS\nexus\Transaction::STATUS_REFUNDED}}2{{else}}6{{endif}}">
	{lang="tstatus_{$status}"}
</span>