<ips:template parameters="$indexData, $itemData, $screenshot, $url, $price, $condensed" />
{{if $condensed}}
	{{if $screenshot}}
		<span class='ipsThumb_bg ipsThumb_small ipsPos_left' style='background-image: url("{file="$screenshot" extension="downloads_Screenshots"}")'>
			<img src='{file="$screenshot" extension="downloads_Screenshots"}' alt='' class="">
		</span>
	{{else}}
		<span class='ipsNoThumb ipsThumb_small ipsPos_left'></span>
	{{endif}}
{{else}}
	<div class='ipsColumns ipsColumns_collapsePhone'>
		<div class='ipsColumn ipsColumn_medium'>
			<a href='{$url}'>
				{{if $screenshot}}
					<img src='{file="$screenshot" extension="downloads_Screenshots"}' class='ipsImage ipsStream_image'>
				{{else}}
					<div class='ipsNoThumb ipsThumb_small'></div>
				{{endif}}
			</a>
		</div>
		<div class='ipsColumn ipsColumn_fluid ipsStream_snippetInfo'>
			<p class='ipsType_reset ipsType_light ipsType_normal'>{lang="version"} {$itemData['file_version']}</p>
			{{if !$price or in_array( 'downloads', explode( ',', settings.idm_nexus_display ) ) }}
				<p class='ipsType_reset ipsType_normal'><i class='fa fa-download'></i> {lang="num_downloads" pluralize="$itemData['file_downloads']"}</p>
			{{endif}}

			
			{{if trim( $indexData['index_content'] ) !== ''}}
				<div class='ipsSpacer_top ipsSpacer_half ipsType_richText ipsType_break ipsType_medium' {{if !( \IPS\Dispatcher::i()->application->directory == 'core' and \IPS\Dispatcher::i()->module and \IPS\Dispatcher::i()->module->key == 'search' )}}data-ipsTruncate data-ipsTruncate-type='remove' data-ipsTruncate-size='2 lines'{{else}}data-searchable data-findTerm{{endif}}>
					{$indexData['index_content']|raw}
				</div>
			{{endif}}
			
			{{if \IPS\Application::appIsEnabled( 'nexus' ) and settings.idm_nexus_on}}
				<p class='ipsType_large ipsType_reset ipsSpacer_top ipsSpacer_half'>
					<span class='ipsStream_price'>
						{{if $price}}
							{$price|raw}
						{{else}}
							{lang="file_free"}
						{{endif}}
					</span>
				</p>
			{{endif}}
		</div>
	</div>
{{endif}}