<ips:template parameters="$purchase" />
{{$extra = $purchase->clientAreaPage();}}

{theme="ipsfocus_b1"}<h2 class='ipsType_sectionTitle'>{$purchase->name}: {lang="$purchase->getTypeTitle()"}</h2>{theme="ipsfocus_b2"}

<div class='ipsPad ipsClearfix'>

<div class='ipsColumns ipsColumns_collapsePhone cNexusPurchase'>
	<div class='ipsColumn ipsColumn_wide'>
		{{if $image = $purchase->image()}}
			<span class='cNexusPurchase_image' style='background-image: url( "{expression="str_replace( array( '(', ')' ), array( '\(', '\)' ), $image->url )"}" );'>&nbsp;</span>
		{{else}}
			<span class='ipsThumb ipsNoThumb {{if $purchase->type == 'giftvoucher'}}ipsNoThumb_gift{{else}}ipsNoThumb_product{{endif}}'>&nbsp;</span>
		{{endif}}

		<hr class='ipsHr'>

		{{if ( $purchase->expire AND $purchase->canRenewUntil(NULL,TRUE) ) OR $purchase->canCancel()}}
			<ul class='ipsToolList ipsToolList_vertical cNexusPurchase_renewActions'>
				{{if $purchase->expire AND $purchase->canRenewUntil(NULL,TRUE)}}
					<li><a href="{$purchase->url()->setQueryString( 'do', 'renew' )->csrf()}" class='ipsButton ipsButton_important ipsButton_fullWidth ipsButton_small' title="{lang="purchase_renew_now_title"}">{lang="purchase_renew_now"}</a></li>
				{{endif}}
				{{if $purchase->canCancel()}}
					<li><a href="{$purchase->url()->setQueryString( 'do', 'cancel' )->csrf()}" class='ipsButton ipsButton_link ipsButton_fullWidth ipsButton_small' data-confirm data-confirmSubMessage="{lang="purchase_cancel_renewal_confirm"}">{lang="purchase_cancel_renewal"}</a></li>
				{{endif}}
			</ul>
		{{endif}}

		<dl class='ipsList_reset cNexusPurchase_info ipsSpacer_top'>
			<dt class='ipsType_minorHeading'><strong>{lang="ps_start"}</strong></dt>
			<dd class='ipsType_normal'>{$purchase->start->localeDate()}</dd>
			{{if $purchase->expire}}
				<dt class='ipsType_minorHeading'><strong>{lang="ps_expire"}</strong></dt>
				<dd class='ipsType_normal'>{$purchase->expire->localeDate()}</dd>
			{{endif}}
			{{if $purchase->renewals and !$purchase->grouped_renewals}}
				<dt class='ipsType_minorHeading'><strong>{lang="purchase_renewal_terms"}</strong></dt>
				<dd class='ipsType_normal'>{$purchase->renewals}</dd>
			{{endif}}
          	{{if $purchase->billing_agreement}}
				<dt class='ipsType_minorHeading'><strong>{lang="ps_billing_agreement"}</strong></dt>
				<dd class='ipsType_normal ipsType_blendLinks'><a href='{$purchase->billing_agreement->url()}'>{$purchase->billing_agreement->gw_id}</a></dd>
			{{endif}}
		</dl>
	</div>
	<div class='ipsColumn ipsColumn_fluid'>
		<p class='ipsType_reset ipsType_normal'>
			{{if $purchase->cancelled}}
				<span class='ipsBadge ipsBadge_negative'>{lang="purchase_canceled"}</span>&nbsp;
			{{elseif !$purchase->active}}
				<span class='ipsBadge ipsBadge_neutral'>{lang="purchase_expired"}</span>&nbsp;
			{{elseif $purchase->expire}}
				{{if $purchase->grace_period and $purchase->expire->getTimestamp() < time()}}
					<span class='ipsBadge ipsBadge_positive'>{lang="purchase_in_grace_period_front"}</span>&nbsp;
				{{else}}
					<span class='ipsBadge ipsBadge_positive'>{lang="purchase_active"}</span>&nbsp;
				{{endif}}
			{{endif}}
		</p>

		{{if $pendingInvoice = $purchase->invoice_pending}}
			<div class='ipsSpacer_top ipsMessage ipsMessage_info'>
				{lang="purchase_pending_invoice"} {{if $purchase->canView()}}<a href="{$pendingInvoice->checkoutUrl()}" title="{lang="order_pay_now_title"}">{lang="order_pay_now"}</a>{{endif}}
			</div>
		{{endif}}

		{{if $lkey = $purchase->licenseKey()}}
			<div class='ipsAreaBackground_light ipsPad ipsType_center ipsSpacer_top'>
				<h2 class='ipsType_minorHeading ipsSpacer_bottom ipsSpacer_half'>{lang="purchase_license_key"}</h2>
				<div class='ipsType_large ipsType_monospace cNexusLicenseKey'>
					{$lkey->key}
				</div>
			</div>
		{{endif}}

		{{if isset( $extra['packageInfo'] )}}
  			<div class='ipsSpacer_top'>
              <h2 class='ipsType_sectionHead ipsSpacer_bottom ipsSpacer_half'>{lang="purchase_package_info"}</h2>
              <div class='ipsType_normal ipsType_richText ipsContained ipsType_break ipsSpacer_bottom'>
                  {$extra['packageInfo']|raw}
              </div>
			</div>
		{{endif}}

		{{if isset( $extra['purchaseInfo'] )}}
			<div>{$extra['purchaseInfo']|raw}</div>
			<br><br>
		{{endif}}
	</div>
</div>
  
</div>

{theme="ipsfocus_b3"}