<ips:template parameters="$table" />

{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack('your_support_requests')"}

<ul class="ipsToolList ipsToolList_horizontal ipsClearfix ipsSpacer_bottom">
	<li class='ipsToolList_primaryAction'>
		<a class="ipsButton ipsButton_medium ipsButton_important ipsButton_fullWidth" href="{url="app=nexus&module=support&controller=home&do=create" seoTemplate="support_create"}" data-ipsDialog data-ipsDialog-title='{lang="new_request"}'>{lang="new_request"}</a>
	</li>
</ul>

<div class='ipsBox'>
	<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="your_support_requests"}</h2>
	{$table|raw}
</div>