<ips:template parameters="$title,$html,$location=array()" />
<!DOCTYPE html>
<html lang="{expression="\IPS\Member::loggedIn()->language()->bcp47()"}" dir="{{if member.language()->isrtl}}rtl{{else}}ltr{{endif}}">
	<head>
		<title>{expression="output.getTitle( $title )"}</title>
		<!--[if lt IE 9]>
			{{foreach \IPS\Theme::i()->css( 'extra/ie8.css', 'core' ) as $css}}<link rel="stylesheet" type="text/css" href="{$css}">{{endforeach}}
		    <script src="{url="applications/core/interface/html5shiv/html5shiv.js" base="none" protocol="\IPS\Http\Url::PROTOCOL_RELATIVE"}"></script>
		<![endif]-->
		{template="includeMeta" app="core" group="global" location="global" params=""}
		{template="includeCSS" app="core" group="global" location="global" params=""}
		{{if theme.ipsf_backgroundType === 'ipsfocus_backgroundPicker'}}
		<style type='text/css' id='styleBackground'></style>
		{{endif}}
		{template="includeJS" if="theme.js_include != 'footer'" app="core" group="global" location="global" params=""}
		{template="favico" app="core" group="global" location="front" params=""}
	</head>
	<body class='ipsApp ipsApp_front {{if isset( \IPS\Request::i()->cookie['hasJS'] )}}ipsJS_has{{else}}ipsJS_none{{endif}} ipsClearfix{{foreach output.bodyClasses as $class}} {$class}{{endforeach}} {theme="ipsf_backgroundType"} {{if theme.ipsf_valentines}}ipsfocus_valentines{{endif}} {{if theme.ipsf_christmas}}ipsfocus_christmas{{endif}} {{if theme.ipsf_fixedHeader}}ipsfocus_fixedHeader{{endif}} {{if !member.member_id}}ipsfocus_guest{{endif}}' {{if output.globalControllers}}data-controller='{expression="implode( ',', output.globalControllers )"}'{{endif}} {{if isset( output.inlineMessage )}}data-message="{expression="output.inlineMessage"}"{{endif}} data-pageApp='{$location['app']}' data-pageLocation='front' data-pageModule='{$location['module']}' data-pageController='{$location['controller']}' itemscope itemtype="http://schema.org/WebSite">
		<meta itemprop="url" content="{setting="base_url"}">
		<a href='#elContent' class='ipsHide' title='{lang="jump_to_content_desc"}' accesskey='m'>{lang="jump_to_content"}</a>

		<div id='timeGradient'></div>

		<div id='ipsLayout_header' class='ipsClearfix'>
			{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}{template="mobileNavBar" app="core" group="global" params=""}{{endif}}
			<div id='respSearch'></div>
			
			<div class='ipsLayout_container ipsClearfix'>
				<header id='header' class='ipsClearfix'>
					{template="logo" app="core" group="global" params=""}
					{template="searchBar" app="core" group="global" params=""}
				</header>

            	{{if theme.ipsf_fixedHeader}}<div class='fixedWrap'><div class='ipsLayout_container ipsClearfix forceWidth'>{{endif}}<div id='navBar' class='ipsClearfix'>
					{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}{template="userBar" app="core" group="global" params=""}{{endif}}
                    {template="navBar" app="core" group="global" params=""}
              	</div>{{if theme.ipsf_fixedHeader}}</div></div>{{endif}}
			</div>
			
		</div>
		
		<main role='main' id='ipsLayout_body' class='ipsLayout_container'>
			<div id='ipsLayout_contentArea'>
				<div class='preContentPadding'>
                    {template="ipsfocus_backgroundPicker" if="theme.ipsf_backgroundType == 'ipsfocus_backgroundPicker'" app="core" group="global" params=""}
                    <!-- Breadcrumbs -->
                    <div class='ipsfocus_breadcrumbWrap ipsClearfix'>
                    	{template="ipsfocus_socialButtons" if="theme.ipsf_social" app="core" group="global" params=""}
                    	{template="breadcrumb" app="core" group="global" params="true, 'top'"}
                    </div>
					{template="ipsfocus_globalMessage" if="theme.globalMessage" app="core" group="global" params=""}
                    {{if !member.member_id}}{template="ipsfocus_guestMessage" if="theme.ipsf_guest" app="core" group="global" params=""}{{endif}}
                    {template="ipsfocus_countdown" if="theme.ipsf_countdown" app="core" group="global" params=""}
            	</div>
				<div id='ipsLayout_contentWrapper'>
					{template="sidebar" if="theme.sidebar_position == 'left'" app="core" group="global" params="'left'"}
					<div id='ipsLayout_mainArea'>
						<a id='elContent'></a>
						{template="offlineMessage" if="!settings.site_online && \IPS\Member::loggedIn()->group['g_access_offline']" app="core" group="global" params=""}
						{template="updateWarning" app="core" group="global" params=""}
						{template="lkeyWarning" app="core" group="global" location="global" params=""}
						{advertisement="ad_global_header"}
						{template="acknowledgeWarning" if="\IPS\Member::loggedIn()->members_bitoptions['unacknowledged_warnings']" params="\IPS\Member::loggedIn()->warnings( 1, FALSE )" group="global" app="core"}
						{template="widgetContainer" group="global" app="core" params="'header', 'horizontal'"}
						{$html|raw}
						{template="widgetContainer" group="global" app="core" params="'footer', 'horizontal'"}
					</div>
					{template="sidebar" if="theme.sidebar_position == 'right'" app="core" group="global" params="'right'"}
				</div>
                {template="ipsfocus_megaFooter" if="theme.ipsf_megaFooter" app="core" group="global" params=""}
				{template="breadcrumb" app="core" group="global" params="false, 'bottom'"}
			</div>
			{template="inlineMessage" if="member.msg_show_notification and $conversation = \IPS\core\Messenger\Conversation::latestUnreadConversation()" app="core" group="global" params="$conversation->comments( 1, 0, 'date', 'desc' )"}
		</main>
		<div class='ipsLayout_container'><footer id='ipsLayout_footer' class='ipsClearfix'>
				
			{advertisement="ad_global_footer"}
			{template="footer" app="core" group="global" params=""}
			
		</footer></div>
		
		{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}{template="mobileNavigation" if="theme.responsive" app="core" group="global" params=""}{{endif}}
		{template="includeJS" if="theme.js_include == 'footer'" app="core" group="global" location="global" params=""}
		{template="ipsfocus_videoBackground" if="theme.ipsf_backgroundType == 'ipsfocus_videoBackground'" app="core" group="global" params=""}
		{{if settings.ipbseo_ga_enabled}}
			{setting="ipseo_ga"}
		{{endif}}
		{template="viglink" if="settings.viglink_enabled" app="core" group="global" params=""}
		{template="metaTagEditor" if="isset( $_SESSION['live_meta_tags'] ) and $_SESSION['live_meta_tags'] and member.isAdmin()" app="core" group="global" params=""}
		<!--ipsQueryLog-->
		<!--ipsCachingLog-->
		{expression="output.endBodyCode" raw="true"}
	</body>
</html>