<ips:template parameters="" />
<div class='ipsfocus_{theme="ipsf_guestStyle"}'>
	<div class="ipsfocus_guestHeader">Welcome to {setting="board_name"}</div>
    <div class='ipsfocus_guestText'>{theme="ipsf_guestText"}</div>
    <div class='ipsfocus_guestButtons'>
		<a href="{url="app=core&module=system&controller=login" seoTemplate="login"}" class="guestButton">{lang="login"}</a> <a href="{url="app=core&module=system&controller=register" seoTemplate="register"}" class="guestButton ipsfocus_register">{lang="sign_up"}</a>
    </div>
</div>