<ips:template parameters="" />
<div id='ipsf_pickerWrap'>
	<div id='ipsf_picker' class='ipsClearfix'>
	    <span data-backgroundClass='ipsfocus_bg1' style='background-color: {theme="ifBg1_hex"}; {{if theme.ifBg1_image}}background-image: url({theme="ifBg1_image"});{{endif}} background-position: {theme="ifBg1_position"}; background-size: {theme="ifBg1_size"}'></span>
		<span data-backgroundClass='ipsfocus_bg2' style='background-color: {theme="ifBg2_hex"}; {{if theme.ifBg2_image}}background-image: url({theme="ifBg2_image"});{{endif}} background-position: {theme="ifBg2_position"}; background-size: {theme="ifBg2_size"}'></span>
    	<span data-backgroundClass='ipsfocus_bg3' style='background-color: {theme="ifBg3_hex"}; {{if theme.ifBg3_image}}background-image: url({theme="ifBg3_image"});{{endif}} background-position: {theme="ifBg3_position"}; background-size: {theme="ifBg3_size"}'></span>
	    <span data-backgroundClass='ipsfocus_bg4' style='background-color: {theme="ifBg4_hex"}; {{if theme.ifBg4_image}}background-image: url({theme="ifBg4_image"});{{endif}} background-position: {theme="ifBg4_position"}; background-size: {theme="ifBg4_size"}'></span>
      	<span data-backgroundClass='ipsfocus_bg5' style='background-color: {theme="ifBg5_hex"}; {{if theme.ifBg5_image}}background-image: url({theme="ifBg5_image"});{{endif}} background-position: {theme="ifBg5_position"}; background-size: {theme="ifBg5_size"}'></span>
      	<span data-backgroundClass='ipsfocus_bg6' style='background-color: {theme="ifBg6_hex"}; {{if theme.ifBg6_image}}background-image: url({theme="ifBg6_image"});{{endif}} background-position: {theme="ifBg6_position"}; background-size: {theme="ifBg6_size"}'></span>
	</div>
</div>