<ips:template parameters="$preview=FALSE" />
<div class='navAlign {{if theme.singleNavigationBar}}hiddenLinks{{endif}}'>
{{if !in_array('ipsLayout_minimal', \IPS\Output::i()->bodyClasses )}}
	<nav class='ipsLayout_container resetWidth' {{if !theme.singleNavigationBar}}data-controller='core.front.core.navBar'{{endif}}>
		<div class='ipsNavBar_primary {{if !count( \IPS\core\FrontNavigation::i()->subBars( $preview ) )}}ipsNavBar_noSubBars{{endif}} ipsClearfix'>
			<ul data-role="primaryNavBar" class='{{if !$preview}}ipsResponsive_showDesktop ipsResponsive_block{{endif}}'>
				{template="navBarItems" app="core" group="global" location="front" params="\IPS\core\FrontNavigation::i()->roots( $preview ), \IPS\core\FrontNavigation::i()->subBars( $preview ), 0, $preview"}
              {{if theme.singleNavigationBar}}
              	<li class="focusNav_more focusNav_hidden" data-width="80">
                	<a href="#"> {lang="more"} </a>
                	<ul class='ipsNavBar_secondary'></ul>
                </li>
              {{else}}
				<li class='ipsHide' id='elNavigationMore' data-role='navMore'>
					<a href='#' data-ipsMenu data-ipsMenu-appendTo='#elNavigationMore' id='elNavigationMore_dropdown'>{lang="more"}</a>
					<ul class='ipsNavBar_secondary ipsHide' data-role='secondaryNavBar'>
						<li class='ipsHide' id='elNavigationMore_more' data-role='navMore'>
							<a href='#' data-ipsMenu data-ipsMenu-appendTo='#elNavigationMore_more' id='elNavigationMore_more_dropdown'>{lang="more"} <i class='fa fa-caret-down'></i></a>
							<ul class='ipsHide ipsMenu ipsMenu_auto' id='elNavigationMore_more_dropdown_menu' data-role='moreDropdown'></ul>
						</li>
					</ul>
				</li>
              {{endif}}
			</ul>
		</div>
	</nav>
{{elseif member.group['g_view_board']}}
	<nav class='ipsLayout_container'>
		<div class='ipsNavBar_primary ipsNavBar_noSubBars ipsClearfix'>
          	<ul data-role="primaryNavBar" class='{{if !$preview}}ipsResponsive_showDesktop ipsResponsive_block{{endif}}'>
            	<li><a id='elBackHome' href='{setting="base_url"}' title='{lang="go_community_home"}'> {lang="community_home"} </a></li>
            </ul>
		</div>
	</nav>
{{endif}}
</div>