<ips:template parameters="$image, $slider, $next=NULL, $prev=NULL, $hasNext=TRUE, $hasPrev=TRUE, $commentsAndReviews=FALSE" />
<div data-controller='gallery.front.view.image'>
	<div id='elGalleryHeader'>
		{template="imageFrame" group="view" app="gallery" params="$image, $slider, $next, $prev"}
		<div id='elGalleryNav' data-role='collectionNav'>
			<ul class='ipsList_inline ipsClearfix'>
				{template="imageSlider" group="view" app="gallery" params="$image, $slider, $next, $prev, $hasNext, $hasPrev"}
			</ul>
			<p class='ipsType_reset ipsType_center'>
				{lang="slider_text" sprintf="$image->directContainer()->_title"}
			</p>
		</div>
	</div>

	<section data-role='imageInfo'>
		{template="imageInfo" group="view" params="$image, $slider, $next, $prev"}	
	</section>

  	{{if $commentsAndReviews}}
	<div data-role='imageComments' class='ipsSpacer_top'>
		{{if ( $image->directContainer()->allow_reviews && $image->container()->allow_reviews ) && ( $image->directContainer()->allow_comments && $image->container()->allow_comments ) }}
			<a id="replies"></a>
			{theme="ipsfocus_b1"}<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="user_feedback"}</h2>{theme="ipsfocus_b2"}
		{{endif}}
		{$commentsAndReviews|raw}
      {{if ( $image->directContainer()->allow_reviews && $image->container()->allow_reviews ) && ( $image->directContainer()->allow_comments && $image->container()->allow_comments ) }}{theme="ipsfocus_b3"}{{endif}}
	</div>
	{{endif}}

</div> 