<ips:template parameters="$featured, $new, $rated, $downloaded" />
<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom">
	<h1 class="ipsType_pageTitle">{lang="downloads"}</h1>
</div>
<a href='#elDownloadsCategories_menu' data-ipsMenu id='elDownloadsCategories' class='ipsButton ipsButton_light ipsButton_small ipsButton_fullWidth ipsResponsive_hideDesktop ipsResponsive_block ipsSpacer_bottom'><span class='ipsType_light'>{lang="downloads_category_select"}&nbsp;&nbsp;</span> {lang="all"} <i class='fa fa-caret-down'></i></a>
{template="categoryMenu" group="browse" params="\IPS\downloads\Category::roots()"}

{{if !empty( $featured )}}
	<div class='ipsBox ipsSpacer_bottom'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="featured_downloads"}</h2>
		<section id='elDownloadsFeatured'>
			<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-fullSizeItems data-ipsCarousel-slideshow data-ipsCarousel-shadows='false'>
				<ul class='cDownloadsCarousel ipsClearfix' data-role="carouselItems">
					{{foreach $featured as $file}}
						{template="featuredFile" group="browse" app="downloads" params="$file"}
					{{endforeach}}
				</ul>
				<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
				<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
				<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
				<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
			</div>
		</section>
	</div>
{{endif}}

{{if \IPS\downloads\Category::canOnAny('add')}}
	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_hidePhone ipsClearfix ipsSpacer_bottom">
		{template="categoryButtons" group="browse" params="\IPS\downloads\Category::canOnAny('add')"}
	</ul>
{{endif}}
	
	<div class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="browse_whats_new"}</h2>
		<div class='ipsAreaBackground ipsPad_half'>
			{{if count( $new )}}
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<ul class='cDownloadsCarousel' data-role="carouselItems">
						{{foreach $new as $idx => $file}}
							{template="indexBlock" group="browse" params="$file"}
						{{endforeach}}
					</ul>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			{{else}}
				<p class='ipsType_reset ipsType_light ipsPad'>{lang="no_new_files"}</p>
			{{endif}}
		</div>
	</div>

	<div class='ipsBox ipsSpacer_top'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="browse_highest_rated"}</h2>
		<div class='ipsAreaBackground ipsPad_half'>
			{{if count( $rated )}}
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<ul class='cDownloadsCarousel' data-role="carouselItems">
						{{foreach $rated as $idx => $file}}
							{template="indexBlock" group="browse" params="$file"}
						{{endforeach}}
					</ul>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			{{else}}
				<p class='ipsType_reset ipsType_light ipsPad'>{lang="no_rated_files"}</p>
			{{endif}}
		</div>
	</div>

	<div class='ipsBox ipsSpacer_top'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="browse_most_downloaded"}</h2>
		<div class='ipsAreaBackground ipsPad_half'>
			{{if count( $downloaded )}}
				<div class='ipsCarousel ipsClearfix' data-ipsCarousel data-ipsCarousel-showDots>
					<ul class='cDownloadsCarousel' data-role="carouselItems">
						{{foreach $downloaded as $idx => $file}}
							{template="indexBlock" group="browse" params="$file"}
						{{endforeach}}
					</ul>
					<span class='ipsCarousel_shadow ipsCarousel_shadowLeft'></span>
					<span class='ipsCarousel_shadow ipsCarousel_shadowRight'></span>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='prev'><i class='fa fa-chevron-left'></i></a>
					<a href='#' class='ipsCarousel_nav ipsHide' data-action='next'><i class='fa fa-chevron-right'></i></a>
				</div>
			{{else}}
				<p class='ipsType_reset ipsType_light ipsPad'>{lang="no_downloaded_files"}</p>
			{{endif}}
		</div>
	</div>

{{if \IPS\downloads\Category::canOnAny('add')}}
	<ul class="ipsToolList ipsToolList_horizontal ipsResponsive_showPhone ipsResponsive_block ipsClearfix ipsSpacer_top">
		{template="categoryButtons" group="browse" params="\IPS\downloads\Category::canOnAny('add')"}
	</ul>
{{endif}}