<ips:template parameters="$baseUrl" />
{{if count( \IPS\nexus\Money::currencies() ) > 1}}
	{{$memberCurrency = ( ( isset( $_SESSION['currency'] ) and in_array( $_SESSION['currency'], \IPS\nexus\Money::currencies() ) ) ? $_SESSION['currency'] : \IPS\nexus\Customer::loggedIn()->defaultCurrency() );}}
	<div class='ipsType_center ipsAreaBackground_light ipsPad ipsSpacer_top ipsSpacer_half' {{if isset( $_SESSION['cart'] ) and count( $_SESSION['cart'] )}}data-controller="nexus.front.store.currencySelect"{{endif}}>
		<span class='ipsType_normal'>{lang="show_prices_in"}</span><br>
		<ul class='ipsList_inline'>
			{{foreach \IPS\nexus\Money::currencies() as $currency}}
				<li>	
					{{if $currency == $memberCurrency}}
						<a href='{$baseUrl->setQueryString( 'currency', $currency )->csrf()}' class='ipsType_blendLinks' title='{lang="set_currency_to" sprintf="$currency"}'>
							<strong><i class='fa fa-check'></i> {$currency}</strong>
						</a>
					{{else}}
						<a href='{$baseUrl->setQueryString( 'currency', $currency )->csrf()}' title='{lang="set_currency_to" sprintf="$currency"}'>{$currency}</a>
					{{endif}}
				</li>
			{{endforeach}}
		</ul>
	</div>
{{endif}}