<ips:template parameters="$id, $extra=''" />
<div class="ipsPad">
	<p class="ipsType_normal">{lang="ads_disabled"}</p>
</div>
<div class="ipsAreaBackground_light ipsClearfix ipsPad ipsType_center">
	<a href="{url="&app=core&module=promotion&controller=advertisements"}" target="_blank" class="ipsButton ipsButton_alternate">{lang="ads_disabled_go_ads"}</a>
	<a href="{url="app=core&module=support&controller=support&next={$id}&mr=1{$extra}"}" data-action="redirectContinue" class="ipsButton ipsButton_primary">{lang="problem_not_resolved"}</a>
</div>